blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/TheCoder1232/RTunes/discussions
    about: For questions and general discussion that don't fit a bug report or feature request.
